--------------------------------------------------------
--  File created - Wednesday-May-22-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EVENTS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."EVENTS" 
   (	"EVENTID" NUMBER(30,0), 
	"EVENTNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"EVENTDATE" DATE, 
	"SEATS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CHARGES" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"BOOKINGS" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.EVENTS
SET DEFINE OFF;
Insert into ADMIN.EVENTS (EVENTID,EVENTNAME,EVENTDATE,SEATS,LOCATION,CHARGES,BOOKINGS) values (1,'Jazz Festival',to_date('25-MAY-19','DD-MON-RR'),'200','Green Hours Jazz Cafe','60',64);
Insert into ADMIN.EVENTS (EVENTID,EVENTNAME,EVENTDATE,SEATS,LOCATION,CHARGES,BOOKINGS) values (21,'Wellness Festival',to_date('25-JUL-19','DD-MON-RR'),'100','Bucharest','30',6);
Insert into ADMIN.EVENTS (EVENTID,EVENTNAME,EVENTDATE,SEATS,LOCATION,CHARGES,BOOKINGS) values (30,'Concours d''Elegence',to_date('17-JUL-19','DD-MON-RR'),'100','Sala Palatui','50',8);
Insert into ADMIN.EVENTS (EVENTID,EVENTNAME,EVENTDATE,SEATS,LOCATION,CHARGES,BOOKINGS) values (35,'Encore Metal Show',to_date('19-JUL-19','DD-MON-RR'),'100','Quantic Club','50',1);
--------------------------------------------------------
--  DDL for Index ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."ID" ON "ADMIN"."EVENTS" ("EVENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EVENTS" MODIFY ("EVENTID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EVENTS" ADD CONSTRAINT "ID" PRIMARY KEY ("EVENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
